<# setup.ps1 — VPX + RL — use your newest Python (e.g., 3.14) #>

param(
  [string]$VPXPath   = "C:\Visual Pinball\VPinballX.exe",
  [string]$TablePath = "$PSScriptRoot\pinballTable.vpx",
  [int]$BridgePort   = 5000
)

$ErrorActionPreference = "Stop"

function Find-Python {
  if (Get-Command py -ErrorAction SilentlyContinue) { return "py" }
  if (Get-Command python -ErrorAction SilentlyContinue) { return "python" }
  throw "Python is not installed. Install it and re-run."
}

function New-VenvCurrent {
  param([string]$PyCmd)
  if (Test-Path ".\.venv") { return }
  Write-Host 'Creating .venv with your current Python ...'
  if ($PyCmd -eq "py") {
    py -m venv .venv
  } else {
    & $PyCmd -m venv .venv
  }
}

function Pip-Install {
  $py = ".\.venv\Scripts\python.exe"
  if (-not (Test-Path $py)) { throw "Virtualenv python not found at $py" }

  & $py -m pip install --upgrade pip wheel setuptools

  if (Test-Path ".\requirements.txt") {
    & $py -m pip install -r .\requirements.txt
  } else {
    & $py -m pip install flask requests numpy gymnasium
    try {
      & $py -m pip install "torch==2.9.0" --timeout 120
    } catch {
      Write-Host 'PyPI torch install failed — retrying from the PyTorch index (CPU wheels) ...'
      & $py -m pip install "torch==2.9.0" --index-url https://download.pytorch.org/whl/cpu --timeout 120
    }
  }
}

function Write-Env {
  $pyexe = (Resolve-Path .\.venv\Scripts\python.exe)
  $root  = (Resolve-Path .)

  $lines = @()
  $lines += '# Generated by setup.ps1'
  $lines += ('VPX_PATH="{0}"' -f $VPXPath)
  $lines += ('VPX_TABLE="{0}"' -f $TablePath)
  $lines += ('BRIDGE_PORT={0}' -f $BridgePort)
  $lines += ('PYTHON_EXE="{0}"' -f $pyexe)
  $lines += ('PROJECT_ROOT="{0}"' -f $root)

  Set-Content -Path ".env" -Value $lines -Encoding UTF8
  Write-Host 'Wrote .env'
}

Write-Host '=== VPX RL Setup (current Python) ==='

$pycmd = Find-Python
New-VenvCurrent -PyCmd $pycmd
Pip-Install

if (-not (Test-Path ".\requirements.txt")) {
  $req = @(
    "flask",
    "requests",
    "numpy",
    "gymnasium",
    "torch==2.9.0"
  )
  Set-Content -Path ".\requirements.txt" -Value $req -Encoding UTF8
}

Write-Env
Write-Host 'Setup complete. Next: double-click run_all.ps1'
